### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by robertFreiseisen** [CodeChrisB/bookless#1]
- [x] Technology choice
- [x] ERD
- [x] create SQL - Files

**Comment by CodeChrisB** [comment]
You could add checkboxes for all 4 members of buchfrei, wether we have installed the sql things you are talking about.

I guess its currently not defined what we should install please add TBD (to be defined) to make it clear.
 
Kind regards ChrisB🐟👍🏼

**Comment by robertFreiseisen** [comment]
Hey guys  here a Docker-Tutorial [https://www.youtube.com/watch?v=fqMOX6JJhGo](url)

**Comment by robertFreiseisen** [comment]
We will use PostgreSQL!!! :)

**Comment by CodeChrisB** [comment]
Okay, I guess we'll scrap the idea of using an Raspberry Pi as server ?

**Comment by robertFreiseisen** [comment]
Done
