### ISSUE TITLE
Fix Services for Backend

### ISSUE THREAD

**Issue by CodeChrisB** [CodeChrisB/bookless#103]
We have  problems with the static methods inside the services

**Comment by CodeChrisB** [comment]
# Current Status at the end of Sprint 6
|Service |Fixed|
|-|-|
|Private Customer|✔️|
|Company Customer|❌|

### What are the problems we have to face?

- Connection of Company Customer
   - Static Methods for data transmission to Frontend Component
      - This will be done in the next Sprint
### Things to consider
- Thoughts about  a different Service System
    - Main Service which calls the other services

**Comment by robertFreiseisen** [comment]
## Status update at the beginning of Sprint 7
|Service |Fixed|
|-|-|
|Private Customer|✔️|
|Company Customer|❌|


- update of the Customers doesn't work
- add of the Customers work
- Customers shown in the components
