### ISSUE TITLE
Css overhaul Bill Input Mask

### ISSUE THREAD

**Issue by CodeChrisB** [CodeChrisB/bookless#123]
Checkout the input mask of the Private customer and use this as a template how the new Bill Mask should look

Thats the Private Customer Add Component
![grafik](https://user-images.githubusercontent.com/55576076/121019048-5da8c080-c79f-11eb-967d-392de8f02725.png)

Thats the current design of the Bill Mask

![grafik](https://user-images.githubusercontent.com/55576076/121019332-9cd71180-c79f-11eb-8e36-e24eeb91e8ff.png)

**Comment by SebastianEgg** [comment]
Done
