### ISSUE TITLE
Css overhaul Input Mask Products

### ISSUE THREAD

**Issue by CodeChrisB** [CodeChrisB/bookless#124]
## Change the Input Mask of the  Product/Wärmetauscher Add Page

You have alot of artistic freedom but your boundaries are to fit the other Add Components, which may or may not limit those freedom

You may use ```mat-menu``` even though you may not use multiple tabs.

#### The current look :
![grafik](https://user-images.githubusercontent.com/55576076/121019994-356d9180-c7a0-11eb-85da-17dbd8a5f797.png)

**Comment by CodeChrisB** [comment]
Issuse is now for @SebastianEgg

**Comment by CodeChrisB** [comment]
## The New Design for the Product Input Mask
- Desc  --> A small description of the product
- Std Preis--> the price of the product
- Bild --> The image Component from the Profile Page
![grafik](https://user-images.githubusercontent.com/55576076/121527116-5c270480-c9fa-11eb-95e8-a6370dac273c.png)

**Comment by SebastianEgg** [comment]
Done on 10.6.2021
