### ISSUE TITLE
Set Up Docker

### ISSUE THREAD

**Issue by robertFreiseisen** [CodeChrisB/bookless#20]
**SetUp Docker**
- Install Docker like in BooklessDocs

**Done on Divice**
- [x] Aigner
- [x] Buchberger
- [x] Egger
- [x] Freiseisen

**Comment by CodeChrisB** [comment]
I see no reason for any linux distribution, docker can be run on windows aswell.

**Comment by robertFreiseisen** [comment]
Until now I have not managed to run docker on windows

**Comment by SebastianEgg** [comment]
Docker is installed on all Laptops.
