### ISSUE TITLE
Write UI Guide

### ISSUE THREAD

**Issue by PS-Support** [CodeChrisB/bookless#6]
Hello Guys!

Please Write a UI Guide, it should contain :

- Who is the main designer?
- Explain briefly the color scheme
- Set up some rules (there are a lot of design rules online)

**Comment by CodeChrisB** [comment]
#### Welcome in the team!

This design guide will be created on thrusday, it should be online in the BooklessDocs repo on friday 2pm !

By the way I am the main Designer.
